# Generated by Django 5.0.4 on 2025-07-01 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='質問内容')),
                ('category', models.CharField(choices=[('styling', 'スタイリング'), ('coordination', 'コーディネート'), ('brand', 'ブランド'), ('size', 'サイズ'), ('care', 'お手入れ'), ('trend', 'トレンド'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('status', models.CharField(choices=[('open', '回答受付中'), ('closed', '解決済み'), ('expired', '期限切れ')], default='open', max_length=10, verbose_name='ステータス')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='画像')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='閲覧数')),
                ('answers_count', models.PositiveIntegerField(default=0, verbose_name='回答数')),
                ('reward_points', models.PositiveIntegerField(default=10, verbose_name='回答報酬ポイント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/', verbose_name='画像')),
                ('is_helpful', models.BooleanField(default=False, verbose_name='役立った回答')),
                ('is_best_answer', models.BooleanField(default=False, verbose_name='ベストアンサー')),
                ('helpful_votes', models.PositiveIntegerField(default=0, verbose_name='役立った投票数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.question')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-is_best_answer', '-helpful_votes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True, verbose_name='役立った')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票日時')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='answers.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '回答投票',
                'verbose_name_plural': '回答投票',
                'unique_together': {('answer', 'user')},
            },
        ),
    ]
