# Generated by Django 5.2 on 2025-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="recommended_products",
            field=models.JSONField(
                blank=True, help_text="回答で紹介した商品のID配列", null=True, verbose_name="推奨商品"
            ),
        ),
    ]
