# Generated by Django 5.0.4 on 2025-06-26 09:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ブランド名')),
                ('description', models.TextField(blank=True, verbose_name='ブランド説明')),
                ('website_url', models.URLField(blank=True, verbose_name='公式サイト')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='ロゴ画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ブランド',
                'verbose_name_plural': 'ブランド',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='価格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='元値')),
                ('description', models.TextField(verbose_name='商品説明')),
                ('condition', models.CharField(choices=[('new', '新品'), ('like_new', 'ほぼ新品'), ('good', '良い'), ('fair', '普通'), ('poor', '悪い')], max_length=20, verbose_name='状態')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('FREE', 'フリーサイズ')], max_length=10, verbose_name='サイズ')),
                ('color', models.CharField(max_length=50, verbose_name='色')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='素材')),
                ('main_image', models.ImageField(upload_to='items/', verbose_name='メイン画像')),
                ('is_available', models.BooleanField(default=True, verbose_name='販売中')),
                ('is_featured', models.BooleanField(default=False, verbose_name='おすすめ商品')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.brand', verbose_name='ブランド')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/', verbose_name='画像')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='items.item', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品追加画像',
                'verbose_name_plural': '商品追加画像',
                'ordering': ['order'],
            },
        ),
    ]
