# Generated by Django 5.2 on 2025-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="main_image_url",
            field=models.URLField(blank=True, null=True, verbose_name="メイン画像URL"),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="items/", verbose_name="メイン画像"
            ),
        ),
    ]
